### ISSUE TITLE
DPL-876 As PSD we would like to upgrade GateKeeper to Ruby 3 and Rails 7 so that we keep up to date with our dependencies.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/gatekeeper#319]
**Describe the Housekeeping**
As PSD we would like to upgrade GateKeeper to Ruby 3 and Rails 7 so that we keep up to date with our dependencies.

**Blocking issues**
We need to do this if we don't do #100 

- [ ] Review and update any other dependencies that require updating as part of this process.
- [ ] Ensure any existing unit and integration tests pass

**Comment by KatyTaylor** [comment]
I've put this as medium because a) it's already on Ruby 3, and b) if we do it after https://github.com/sanger/samples_extraction/issues/277 then we'll have prior experience upgrading to Rails 7.

**Comment by TWJW-SANGER** [comment]
Closing this as it is in Done
