### ISSUE TITLE
Y24-255 - [BUG] Gatekeeper Exception

### ISSUE THREAD

**Issue by harrietc52** [sanger/gatekeeper#430]
**Describe the bug**

A reoccurring exception is being thrown from Gatekeeper. (~52 occurrences since 2021)

e.g. 13/08/24

[Gatekeeper PRODUCTION] barcode_labels#create (NoMethodError) "undefined method `map' for #<ActionController::Parameters…

A NoMethodError occurred in barcode_labels#create:

e.g. undefined method `map' for #<ActionController::Parameters {"61056"=>"61056"} permitted: false>
  app/controllers/barcode_labels_controller.rb:30:in `generate_labels'

e.g. undefined method `map' for #<ActionController::Parameters {"44310"=>"44310", "44311"=>"44311", "44312"=>"44312", "44313"=>"44313", "44314"=>"44314", "44315"=>"44315"} 

Look into what is causing this exception and discuss whether the fix is worthwhile with the team

**Comment by harrietc52** [comment]
Closing as not part of the Exception Handling Process Trial

**Comment by stevieing** [comment]
duplicate of [#437](https://github.com/sanger/gatekeeper/issues/437)
